### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by VinnyOG** [aplabs/bsos-paper#1]
This paper is due on turnitin over the weekend. I spoke with Mr Walker and as it turns out, we can submit one big paper and each have our own sections ('mini papers').

**Comment by a7a00** [comment]
Wait, over the weekend? Is that Saturday, Sunday? When is the hard and fast due date?

Also, what's the TurnItIn username/password, again?

**Comment by a7a00** [comment]
All right, looks like Pawel and I are almost done. @woodruffw and Reyna, how are you guys coming along?
